services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  spring-server:
    build: ./server
    image: frostdocker273/springular-server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SECURITY_JWT_SECRET=ff197a90a6248fedd9d73e10d316fc31ef6ba3393dbef69682561ac7ce4c9016
      - SECURITY_JWT_EXPIRATION_ACCESS=1800000
      - SECURITY_JWT_EXPIRATION_REFRESH=604800000
      - CORS_ALLOWED_ORIGINS=http://localhost:4200
  angular-client:
    build: ./client
    image: frostdocker273/springular-client
    ports:
      - "4200:4200"
    depends_on:
      - spring-server

volumes:
  db-data:
    name: "springular-db-volume"