services:
  postgres-database:
    image: "postgres"
    container_name: dev-postgres-database
    ports:
      - "5432:5432"
    volumes:
      - database-shared:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  spring-server:
    build: ./server
    image: frostdocker273/springular-server
    container_name: dev-spring-server
    ports:
      - "8080:8080"
    depends_on:
      - postgres-database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_SECURITY_JWT_SECRET=ff197a90a6248fedd9d73e10d316fc31ef6ba3393dbef69682561ac7ce4c9016
      - SPRING_SECURITY_JWT_EXPIRATION_ACCESS=1800000
      - SPRING_SECURITY_JWT_EXPIRATION_REFRESH=604800000
      - SPRING_SECURITY_CORS_ALLOWED_ORIGINS=*

  angular-client:
    build: ./client
    container_name: dev-angular-client
    image: frostdocker273/springular-client
    ports:
      - "4200:4200"
    depends_on:
      - spring-server

volumes:
  database-shared:
    name: "springular-postgres-volume"
