services:
  database:
    hostname: ${DOCKER_SERVICES_DATABASE_HOSTNAME}
    image: ${DOCKER_SERVICES_DATABASE_IMAGE}
    container_name: ${DOCKER_SERVICES_DATABASE_CONTAINER_NAME}
    env_file: .env
    ports:
      - ${DOCKER_SERVICES_DATABASE_PORTS}
    volumes:
      - database-shared:${DOCKER_SERVICES_DATABASE_VOLUMES_PATH}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  server:
    build: .
    image: ${DOCKER_SERVICES_SERVER_IMAGE}
    container_name: ${DOCKER_SERVICES_SERVER_CONTAINER_NAME}
    ports:
      - ${DOCKER_SERVICES_SERVER_PORTS}
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_SECURITY_JWT_SECRET=${SPRING_SECURITY_JWT_SECRET}
      - SPRING_SECURITY_JWT_EXPIRATION_ACCESS=${SPRING_SECURITY_JWT_EXPIRATION_ACCESS}
      - SPRING_SECURITY_JWT_EXPIRATION_REFRESH=${SPRING_SECURITY_JWT_EXPIRATION_REFRESH}
      - SPRING_SECURITY_CORS_ALLOWED_ORIGINS=${SPRING_SECURITY_CORS_ALLOWED_ORIGINS}

volumes:
  database-shared:
    name: ${DOCKER_VOLUMES_DATABASE_SHARED_NAME}
