name: Spring Boot Server Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test Spring Boot Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: 22
          cache: "gradle"
          cache-dependency-path: |
            server/*.gradle*
            server/**/gradle-wrapper.properties

      - name: Install dependencies and build
        working-directory: server
        run: ./gradlew clean build --no-daemon -x test

      - name: Test
        working-directory: server
        run: ./gradlew test --no-daemon
